language: r
r:
    - devel
    - release
sudo: false
cache: packages

env:
  matrix:
    - NOT_CRAN="true"
    - NOT_CRAN="false"


addons:
  apt:
    packages:
    - texlive-latex-extra

r_binary_packages:
  - Rcpp
  - lme4
  - testthat
  - knitr
  - rmarkdown
  - mvtnorm
  - lattice
  - shiny
  - abind
  - ggplot2
  - dplyr
  - data.table
  - magrittr
  - doParallel
  - covr

script :
 - travis_wait 30 R CMD build --no-build-vignettes --no-manual
 - travis_wait 30 R CMD check merTools_0.4.1.tar.gz --no-build-vignettes --no-manual

after_success:
  - travis_wait Rscript -e 'library(covr);coveralls()'

after_failure:
  - cat merTools.Rcheck/00*

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only: master
