language: r
r:
    - devel
    - release
sudo: false
cache: packages

env:
  matrix:
    - NOT_CRAN="true"
    - NOT_CRAN="false"

after_success:
  - travis_wait Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only: master
