language: r
r: devel
# sudo: required
# cache: packages

env:
  global:
    - WARNINGS_ARE_ERRORS=1
  matrix:
    - NOT_CRAN="true"
    - NOT_CRAN="false"

r_binary_packages:
  - Rcpp
  - lme4
  - testthat
  - knitr
  - rmarkdown
  - mvtnorm
  - lattice
  - shiny
  - plyr
  - abind
  - ggplot2
  - dplyr
  - data.table
  - magrittr
  - doParallel
  - covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

after_failure:
  - cat merTools.Rcheck/00*

notifications:
  email:
    on_success: change
    on_failure: change
